##CONFIG V1.0

#Put your account Link in this section

Discord: http://discord.mythictales.it
Instagram: mcmythictales
InstagramLink: https://www.instagram.com/mcmythictales/
TikTok: mythic_tales
TikTokLink: https://www.tiktok.com/@mythic_tales
Forum: https://forum.mythictales.it/index.php
Website: https://home.mythictales.it/

